# Generated by Django 3.2.5 on 2021-10-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='coding', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
