# Generated by Django 4.2.7 on 2024-11-03 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = []
