# Generated by Django 4.2.7 on 2024-11-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_auto_20241103_2215"),
    ]

    operations = []
